### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\khati\\GITHUB\\python\\dataset\\netflix_titles_2021.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### Check dataset info & missing values

In [5]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

#### Handle missing value

In [6]:
df.fillna("Unknown", inplace=True)

In [7]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

#### Movies vs TV Shows Count

In [13]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

#### Top 10 Directors with Most Content

In [15]:
df["director"].value_counts().drop("Unknown").head(10)

director
Rajiv Chilaka             19
RaÃºl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Martin Scorsese           12
Youssef Chahine           12
Jay Chapman               12
Steven Spielberg          11
Name: count, dtype: int64

#### Which Country Produces Most Netflix Content?

In [17]:
df["country"].value_counts().drop("Unknown").head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

#### Extract numerical duration

In [30]:
df['duration'].value_counts()

duration
1.0      1793
2.0       425
3.0       200
90.0      152
97.0      146
         ...
228.0       1
18.0        1
205.0       1
201.0       1
191.0       1
Name: count, Length: 210, dtype: int64

In [24]:
df["duration"] = df["duration"].str.extract(r'(\d+)').astype(float)

In [25]:
df['duration']

0        90.0
1         2.0
2         1.0
3         1.0
4         2.0
        ...
8802    158.0
8803      2.0
8804     88.0
8805     88.0
8806    111.0
Name: duration, Length: 8807, dtype: float64

#### Find all Netflix Originals (where country = India & type = Movie)

In [33]:
netflix_originals = df[(df["country"] == "India") & (df["type"] == "Movie")]
netflix_originals

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166.0,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,2021.0,9.0
105,s106,Movie,Angamaly Diaries,Lijo Jose Pellissery,"Antony Varghese, Reshma Rajan, Binny Rinky Ben...",India,2021-09-05,2017,TV-14,128.0,"Action & Adventure, Comedies, Dramas",After growing up amidst the gang wars of his h...,2021.0,9.0
114,s115,Movie,Anjaam,Rahul Rawail,"Madhuri Dixit, Shah Rukh Khan, Tinnu Anand, Jo...",India,2021-09-02,1994,TV-14,143.0,"Dramas, International Movies, Thrillers",A wealthy industrialistâ€™s dangerous obsession ...,2021.0,9.0
116,s117,Movie,Dhanak,Nagesh Kukunoor,"Krrish Chhabria, Hetal Gada, Vipin Sharma, Gul...",India,2021-09-02,2015,TV-PG,114.0,"Comedies, Dramas, Independent Movies",A movie-loving 10-year-old and her blind littl...,2021.0,9.0
118,s119,Movie,Gurgaon,Shanker Raman,"Akshay Oberoi, Pankaj Tripathi, Ragini Khanna,...",India,2021-09-02,2017,TV-14,106.0,"Dramas, International Movies, Thrillers",When the daughter of a wealthy family returns ...,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,s8773,Movie,Yamla Pagla Deewana 2,Sangeeth Sivan,"Dharmendra, Sunny Deol, Bobby Deol, Neha Sharm...",India,2017-05-01,2013,TV-14,147.0,"Action & Adventure, Comedies, International Mo...","Up to his old tricks, con man Dharam poses as ...",2017.0,5.0
8773,s8774,Movie,Yanda Kartavya Aahe,Kedar Shinde,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,2018-01-01,2006,TV-PG,151.0,"Comedies, Dramas, International Movies",Thanks to an arranged marriage that was design...,2018.0,1.0
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,2019-12-31,2014,TV-MA,131.0,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...,2019.0,12.0
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,2018-02-15,2009,TV-14,120.0,"Dramas, International Movies",A change in the leadership of a political part...,2018.0,2.0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111.0,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0

#### Filter TV Shows with More than 5 Seasons

In [34]:
df[(df["type"] == "TV Show") & (df["duration"] > 5)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9.0,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021.0,9.0
55,s56,TV Show,Nailed It,Unknown,"Nicole Byer, Jacques Torres",United States,2021-09-15,2021,TV-PG,6.0,Reality TV,Home bakers with a terrible track record take ...,2021.0,9.0
65,s66,TV Show,Numberblocks,Unknown,"Beth Chalmers, David Holt, Marcel McCalla, Ter...",United Kingdom,2021-09-15,2021,TV-Y,6.0,Kids' TV,"In a place called Numberland, math adds up to ...",2021.0,9.0
67,s68,TV Show,Saved by the Bell,Unknown,"Mark-Paul Gosselaar, Tiffani Thiessen, Mario L...",United States,2021-09-15,1994,TV-PG,9.0,"Kids' TV, TV Comedies","From middle school to college, best friends Za...",2021.0,9.0
82,s83,TV Show,Lucifer,Unknown,"Tom Ellis, Lauren German, Kevin Alejandro, D.B...",United States,2021-09-10,2021,TV-14,6.0,"Crime TV Shows, TV Comedies, TV Dramas","Bored with being the Lord of Hell, the devil r...",2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8189,s8190,TV Show,The Andy Griffith Show,Unknown,"Andy Griffith, Ron Howard, Don Knotts, Frances...",United States,NaT,1967,TV-G,8.0,"Classic & Cult TV, TV Comedies",Homespun humor and easygoing Sheriff Andy Tayl...,NaN,NaN
8378,s8379,TV Show,The L Word,Unknown,"Jennifer Beals, Leisha Hailey, Laurel Holloman...","Canada, United States",NaT,2009,TV-MA,6.0,"Romantic TV Shows, TV Dramas",This trailblazing series follows the tangled l...,NaN,NaN
8442,s8443,TV Show,The Office (U.S.),Unknown,"Steve Carell, John Krasinski, Jenna Fischer, R...",United States,NaT,2012,TV-14,9.0,TV Comedies,This hit comedy chronicles the foibles of disg...,NaN,NaN
8557,s8558,TV Show,The West Wing,Unknown,"Martin Sheen, Rob Lowe, Allison Janney, John S...",United States,NaT,2005,TV-14,7.0,TV Dramas,This powerful political epic chronicles the tr...,NaN,NaN
8710,s8711,TV Show,Weeds,Unknown,"Mary-Louise Parker, Hunter Parrish, Alexander ...",United States,2014-04-01,2012,TV-MA,8.0,"TV Comedies, TV Dramas",A suburban mother starts selling marijuana to ...,2014.0,4.0

#### Find all Movies Released after 2020

In [35]:
df[(df["release_year"] > 2020) & (df["type"] == "Movie")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,2021-09-24,2021,PG,91.0,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,2021.0,9.0
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104.0,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021.0,9.0
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127.0,"Dramas, International Movies",After most of her family is murdered in a terr...,2021.0,9.0
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, JÃºlia Gomes, Marc...",Unknown,2021-09-22,2021,TV-PG,91.0,"Children & Family Movies, Comedies",When the clever but socially-awkward TetÃª join...,2021.0,9.0
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",Unknown,2021-09-22,2021,TV-14,94.0,Thrillers,After a deadly home invasion at a coupleâ€™s new...,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,s1426,Movie,Creating The Queen's Gambit,Unknown,Unknown,United States,2021-01-08,2021,TV-14,14.0,Documentaries,A fascinating character. Exquisite sets. A wig...,2021.0,1.0
1431,s1432,Movie,Stuck Apart,Unknown,"Engin GÃ¼naydÄ±n, Haluk Bilginer, Binnur Kaya, Ã–...",Turkey,2021-01-08,2021,TV-MA,97.0,"Comedies, Dramas, International Movies","Entrenched in a midlife crisis, Aziz seeks sol...",2021.0,1.0
1436,s1437,Movie,Ratones Paranoicos: The Band that Rocked Argen...,"Alejandro Ruax, Ramiro MartÃ­nez","Juan SebastiÃ¡n GutiÃ©rrez, Pablo Cano, Pablo Me...",Unknown,2021-01-06,2021,TV-MA,76.0,"Documentaries, International Movies, Music & M...","The irrepressible Ratones Paranoicos, Argentin...",2021.0,1.0
1466,s1467,Movie,The Minimalists: Less Is Now,Unknown,Unknown,United States,2021-01-01,2021,TV-14,54.0,Documentaries,They've built a movement out of minimalism. Lo...,2021.0,1.0
1468,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,2021-01-01,2021,TV-MA,102.0,"Comedies, International Movies","With the peak of his career long behind him, a...",2021.0,1.0